export const TOGGLE_LOADER = 'TOGGLE_LOADER'
export const TOGGLE_AUTH_LOADER = 'TOGGLE_AUTH_LOADER'
export const LOGIN_USER = 'LOGIN_USER'
export const GET_TOP_STORIES = 'GET_TOP_STORIES'
//Search Article
export const GET_ARTICLE_SEARCH = 'GET_ARTICLE_SEARCH'
export const LOAD_MORE_ARTICLES = 'LOAD_MORE_ARTICLES'